### ISSUE TITLE
How to update an existing object using a Mapping?

### ISSUE THREAD

**Issue by thedrow** [timsavage/odin#20]
I have an existing Django model that needs to be updated from a resource.
There seems to be an [update](https://github.com/timsavage/odin/blob/master/odin/mapping/__init__.py#L446) method on the mapping object but there is no documentation describing how to use it.

**Comment by timsavage** [comment]
You instantiate a mapping object and then use the update method eg:

    MyMapping(source_obj).update(target_obj)

**Comment by thedrow** [comment]
Can we add an option to the ```Resource.convert_to``` class to convert to an existing instance?
Something along the lines of:
```python
db_record = DBRecord.objects.get(pk=1)
#...
my_resource.convert_to(db_record)
```

This means that we need to check if the argument is a type or an instance and act accordingly.

**Comment by timsavage** [comment]
Have added an additional method Resource.update_existing to do this. 

Don't really like the idea of overloading the convert_to method, this is less explicit.

**Comment by thedrow** [comment]
Really cool :+1: 
When can I expect a new release?
