### ISSUE TITLE
Resource.to_dict() does not recursively convert nested resources to dictionaries

### ISSUE THREAD

**Issue by thedrow** [timsavage/odin#22]
I expected all to get the entire resource as a dictionary but it seems that the current version odin doesn't do that.
Is that expected behaviour?

**Comment by timsavage** [comment]
That is the expected behaviour. This method is primarily intended for use by the various codecs to get a dictionary version of the resource, the codecs then recursively process each element within the dictionary.

Updated the documentation to indicate this is not recursive.

**Comment by thedrow** [comment]
Would it be possible to make it recursive using a flag?

**Comment by timsavage** [comment]
I would be inclined to make a utility method that is not part of a resource (similar to the various codecs). It is not a feature of a resource to determine how a particular subfield should be transformed into a dict.

Do you have a particular use case in mind?

**Comment by thedrow** [comment]
Yes, printing the resource as a table requires a dictionary.

**Comment by thedrow** [comment]
Also, testing is easier when you can compare dictionaries.

**Comment by timsavage** [comment]
I have started a new dict_codec that will handle this, should have a working solution over the next few days. There are several advantages to this approach, including being able to customise serialisation (if required), and allowing for flags to enable/disable type fields, virtual fields etc.

**Comment by timsavage** [comment]
A version has been committed.

**Comment by thedrow** [comment]
Is it released yet on 0.6? I don't see it.

**Comment by timsavage** [comment]
It is in the master branch. There have been a lot of changes since the last release, I'm in the process of reviewing test and documentation coverage of the new features to ensure they are robust before I do a new release. I'm looking at doing an RC release prior to a full release due to the number of new features.

**Comment by timsavage** [comment]
Tagged a release 0.7b once it's been put through it's passes will update to a final release and deploy to pypi.  You can however use this release in pip by referencing https://github.com/python-odin/odin/archive/release-0.7b.zip

**Comment by thedrow** [comment]
Thanks!
